# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swpp/v1/place.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.type import latlng_pb2 as google_dot_type_dot_latlng__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13swpp/v1/place.proto\x12\x07swpp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18google/type/latlng.proto\"\x83\x01\n\x11ListPlacesRequest\x12/\n\x08location\x18\x01 \x01(\x0b\x32\x13.google.type.LatLngR\x08location\x12=\n\x0crequested_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0brequestedAt\"1\n\x12ListPlacesResponse\x12\x1b\n\tplace_ids\x18\x01 \x03(\x05R\x08placeIds\"\r\n\x0bPingRequest\"(\n\x0cPingResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2\x8e\x01\n\x0cPlaceService\x12G\n\nListPlaces\x12\x1a.swpp.v1.ListPlacesRequest\x1a\x1b.swpp.v1.ListPlacesResponse\"\x00\x12\x35\n\x04Ping\x12\x14.swpp.v1.PingRequest\x1a\x15.swpp.v1.PingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swpp.v1.place_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LISTPLACESREQUEST']._serialized_start=92
  _globals['_LISTPLACESREQUEST']._serialized_end=223
  _globals['_LISTPLACESRESPONSE']._serialized_start=225
  _globals['_LISTPLACESRESPONSE']._serialized_end=274
  _globals['_PINGREQUEST']._serialized_start=276
  _globals['_PINGREQUEST']._serialized_end=289
  _globals['_PINGRESPONSE']._serialized_start=291
  _globals['_PINGRESPONSE']._serialized_end=331
  _globals['_PLACESERVICE']._serialized_start=334
  _globals['_PLACESERVICE']._serialized_end=476
# @@protoc_insertion_point(module_scope)
